export const BillStatusMessage = {
	LAW: 'Became Law',
	GOVERNOR: 'Signed by Governor',
	ZA: 'Executive Signature',
	NG: 'Executive Signature',
	USA: 'Executive Signature',
	DC: 'Executive Signature',
	INTRODUCED: 'Introduced',
	PASSED: 'Passed',
	PASSED_LOWER: 'Passed',
	PASSED_UPPER: 'Passed',
	FIRST_READING: 'First Reading',
	SECOND_READING: 'Second Reading',
	THIRD_READING: 'Third Reading',
	REFERRAL_COMMITTEE: 'Referred to Committee',
	REPORTED_OUT_OF_COMMITTEE: 'Reported out of Committee',
	CONCURRENCE: 'Sent for Concurrence',
	WITHDRAWAL: 'Withdrawn',
	VETOED: 'Vetoed'
};

export const UserFriendlyBillMessage = {
	introduced: 'Bill Introduced',
	passed_upper: 'Passed Upper House',
	passed_lower: 'Passed Lower House',
	passed: 'Passed',
	governor: 'Governor Action',
	law: 'Law Enacted',
	'reading-1': 'First Reading',
	'reading-2': 'Second Reading',
	'reading-3': 'Third Reading',
	'referral-committee': 'Referred to Committee',
	'reported-out-of-committee': 'Reported Out of Committee',
	concurrence: 'Concurrence',
	withdrawal: 'Withdrawal',
	'executive-veto': 'Vetoed',
	'first action': 'First Action',
	'latest action': 'Latest Action',
	'any action': 'Any Action',
	introduction: 'Introduction',
	passage: 'Passage',
	bill: 'Bill',
	'repeal bill': 'Repeal Bill',
	'proposed bill': 'Proposed Bill',
	appropriation: 'Appropriation',
	resolution: 'Resolution',
	'joint resolution': 'Joint Resolution',
	'concurrent resolution': 'Concurrent Resolution',
	'constitutional amendment': 'Constitutional Amendment',
	memorial: 'Memorial',
	'joint memorial': 'Joint Memorial',
	'concurrent memorial': 'Concurrent Memorial',
	petition: 'Petition',
	appointment: 'Appointment',
	memorandum: 'Memorandum',
	commemoration: 'Commemoration',
	proclamation: 'Proclamation',
	remonstration: 'Remonstration',
	nomination: 'Nomination',
	'study request': 'Study Request',
	'concurrent study request': 'Concurrent Study Request',
	contract: 'Contract',
	claim: 'Claim',
	order: 'Order',
	'concurrent order': 'Concurrent Order',
	ordinance: 'Ordinance',
	motion: 'Motion',
	'bill of address': 'Bill of Address',
	other: 'Other'
};
